{
 "title": "Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Select Endpoint", "query": "endpoint_monitoring_bucket" }
  ]
 },
 "panels": [
  {
   "title": "Response Average (ms)",
   "type": "gauge",
   "description": "Overall average response time",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(endpoint_monitoring_sum{http_code=~\"2..\",endpoint_name=\"$endpoint\"}[30m])/rate(endpoint_monitoring_count{http_code=~\"2..\",endpoint_name=\"$endpoint\"}[30m])"
    }
   ]
  },
  {
   "title": "Response Duration",
   "type": "heatmap",
   "description": "Response duration (ms)",
   "gridPos": { "h": 10, "w": 18, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(endpoint_monitoring_bucket{endpoint_name=\"$endpoint\"}[30m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "HTTP 2XX Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(endpoint_monitoring_count{http_code=~\"2..\",endpoint_name=\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "HTTP 4XX Total",
   "type": "stat",
   "description": "Number of HTTP 4XX responses - until now",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(endpoint_monitoring_count{http_code=~\"4..\",endpoint_name=\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "description": "HTTP Response Codes for the last 30 minutes",
   "gridPos": { "h": 10, "w": 18, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(endpoint_monitoring_count{job=\"monitoring\",endpoint_name=\"$endpoint\"}[30m])) by (http_code,path)"
    }
   ]
  },
  {
   "title": "HTTP 5XX Total",
   "type": "stat",
   "description": "Number of HTTP 5XX responses - until now",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(endpoint_monitoring_count{http_code=~\"5..\",endpoint_name=\"$endpoint\"})"
    }
   ]
  }
 ]
}